/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'sessionId' : string, 'items' : Array<CartItem> }
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'name' : string,
  'unit' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[string, string, bigint], undefined>,
  'clearCart' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getCart' : ActorMethod<[string], Cart>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'removeFromCart' : ActorMethod<[string, string], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartQuantity' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];